project:
  type: website
  output-dir: docs

website:
  title: "想東想西"
  favicon: /images/favicon.ico
  navbar:
    title: false
    logo: /images/logo.png
    logo-alt: ""
    left:
      - posts.qmd
      - pubs.qmd
  page-footer: 
    center: Copyright © 2025 Yuchi Chu
   
format:
  html:
    theme:
      light: [flatly, styles.scss] 
    fontsize: 18pt
    linestretch: 1.4
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5em
    toc: true
    language:
      section-title-footnotes: 參考資料
    

editor: visual



