project:
  type: website
  output-dir: docs

website:
  title: "想東想西"
  favicon: /images/favicon.ico
  navbar:
    title: false
    logo: /images/logo.png
    logo-alt: ""
    right:
      - posts.qmd
      - pubs.qmd
  page-footer: 
    center: Copyright © 2025 Yuchi Chu
   
reference-section-title: 参考文獻
bibliography: ref.bib
csl: ieee.csl

format:
  html:
    theme:
      light: [flatly, styles.scss] 
    fontsize: 18pt #equal to font-size in CSS
    linestretch: 1.4 #equal to line-hieght
    grid: #for landing page only
      sidebar-width: 350px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5em
    toc: true
    language:
      section-title-footnotes: 參考資料
      title-block-published: 發布于
    

editor: visual



