project:
  type: website
  output-dir: docs

website:
  title: "Yuchi Chu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - pubs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

