project:
  type: website
  output-dir: docs

website:
  title: "Yuchi's Notes"
  favicon: /images/favicon.ico
  navbar:
    left:
      - posts.qmd
      - pubs.qmd

format:
  html:
    theme:
      light: [flatly, styles.scss] 
    fontsize: "21px"
    linestretch: 1.4
    toc: true

editor: visual

