project:
  type: website
  output-dir: docs

website:
  title: "想東想西"
  favicon: /images/favicon.ico
  navbar:
    title: false
    logo: /images/logo.png
    logo-alt: ""
    left:
      - posts.qmd
      - pubs.qmd
  page-footer: 
    center: Copyright © 2025 Yuchi Chu
   
format:
  html:
    theme:
      light: [flatly, styles.scss] 
    fontsize: "21px"
    linestretch: 1.4
    toc: true
    language:
      section-title-footnotes: 注腳
    

editor: visual



