project:
  type: website
  output-dir: docs

website:
  title: "想東想西"
  favicon: /images/favicon.ico
  navbar:
    left:
      - posts.qmd
      - pubs.qmd

format:
  html:
    theme:
      light: [flatly, styles.scss] 
    fontsize: "21px"
    linestretch: 1.4
    toc: true
    language:
      section-title-footnotes: 註腳
    

editor: visual

