---
title: "論文著作"
description: Publications

#title-block-banner: true
#title-block-banner: "#343a40" #bs-gray-800
---

### 期刊論文

1.  Neng-Huei Lin et al., "An overview of regional experiments on biomass burning aerosols and related pollutants in Southeast Asia: From BASE-ASIA and the Dongsha Experiment to 7-SEAS," *Atmospheric Environment*, Volume 78, (2013) 1-19. [\[LINK\]](https://www.sciencedirect.com/science/article/pii/S1352231013003300)

2.  Samuel A. Atwood, et al., “Size resolved measurements of springtime aerosol particles over the northern South China Sea,”  *Atmospheric Environment*, Vol. 78,  (2013) 134-143. [\[LINK\]](https://www.sciencedirect.com/science/article/abs/pii/S1352231012010862)

3.  朱雨其, 黃素梅, "開放環境資料-現況與未來展望," *國土資訊系統通訊* 第87期, (2013) 33-39. [\[PDF\]](pubs\ngis-2013.pdf)

4.  朱雨其, "環境資訊新服務與展望," *研考雙月刊* 36卷4期, (2012) 102-113.

5.  Sheng-Hsiang Wang, et al., “First detailed observations of long-range transported dust over the northern South China Sea” *Atmospheric Environment*, Vol. 45, (2011) 4804-4808. [\[LINK\]](https://www.sciencedirect.com/science/article/abs/pii/S1352231011004663)

6.  洪啟富, 葉麗雲, 朱雨其, "環境資料檔案之建置與應用," *檔案季刊* 9卷4期, (2010) 28-39. [\[PDF\]](pubs\ar-2010.pdf)

7.  朱雨其, "我國空氣品質監測系統發展概要," *化工技術* 第206期, (2010) 67-79.

8.  朱雨其, "建構環境品質資料倉儲統," *化工技術* 第197期, (2009) 148-164.

9.  葉麗雲, 洪啟富, 詹志銘, 朱雨其, "居家環境與空間資訊加值應用之探討," *國土資訊系統通訊* 第70期, (2009) 73-84. [\[PDF\]](pubs\ngis-2009.pdf)

10. 朱雨其, "資訊技術在環境品質監測之應用," *化工技術* 第181期, (2008) 220-229.

11. 朱雨其, "環境資訊系統 - 現況及未來發展," *工業污染防治* 第97期, (2007) 91-114. [\[PDF\]](pubs\ipp-2007.pdf)

12. Yu-Chi Chu, Shan-Shan Yang, and Chen-Chau Yang, "Enhancing data quality through attribute-based metadata and cost evaluation in data warehouse environments," *Journal of the Chinese Institute of Engineers*, **24:4** (2001) 497-507. [\[PDF\]](pubs\JCIE-2001.pdf)

### 會議論文

1.  Su-Mei Huang and Yu-Chi Chu, "An operation and business model to exchange and open environmental data" (poster), *EnviroInfo & ICT4S*, Copenhagen, Denmark (2015) 207-208. [\[LINK\]](https://dblp.org/rec/conf/enviroinfo/HuangC15.html) [\[PDF\]](pubs\EnviroInfo-2015.pdf)

2.  Su-Mei Huang, Yan-Cin Wang, and Yu-Chi Chu, "Consuming Less Energy and Using Less Floor Space:Taiwan EPA’s Data Center Reconstruction" (poster), 2nd *Conf. of ICT for Sustainability*, Stockholm, Sweden (2014) [\[PDF\]](pubs\ICT4S-2014-3.pdf)

3.  Yu-Chi Chu, Su-Mei Huang, and Chi-Fu Hung "Improving Energy Performance of Data Centers through IT Services Consolidation" (poster), 2nd *Conf. of ICT for Sustainability*, Stockholm, Sweden (2014) [\[PDF\]](pubs\ICT4S-2014-2.pdf)

4.  Yu-Chi Chu and Su-Mei Huang,"Design of a cloud-based system to integrate and share data for environmental governance and sustainability" (poster), 2nd *Conf. of ICT for Sustainability*, Stockholm, Sweden (2014) [\[PDF\]](pubs\ICT4S-2014-1.pdf)

5.  Chi-Fu Hung, Chiu-Ching Tuan, and Yu-Chi Chu, "Constructing a private cloud for government IT services consolidation: Taiwan's experence,"*Proceedings of 5th International Conference on Innovative Mobile and Internet Services in Ubiquitous Computing, IMIS 2011*" Seoul, Korea (2011) 561-566. [\[LINK\]](https://ieeexplore.ieee.org/document/5976274)

6.  朱雨其, "臺灣空氣品質監測系統發展概要," *2010年海峽兩岸沙塵暴防治研討會*, 臺灣臺北 (2010) 1-15. [\[PDF\]](pubs\aq-2010.pdf)

7.  連志誠, 何豈銓, 朱雨其, "保險經紀人異常存取保護資訊之決策分類," *2009 資訊安全實務研討會*, 臺灣臺北 (2009).

8.  葉麗雲, 詹志銘, 朱雨其, "居家環境與空間資訊加值應用之探討," *2008年空間資訊基礎建設國際研討會暨臺灣地理資訊學會年會*, 臺灣臺北, (2008).

9.  Yu-Chi Chu, "A Multi-layered System Architecture for Environmental Monitoring Data Management – Taiwan’s Experience," *Proceedings of 21st International Conference of Informatics for Environmental Protection*, Warsaw, Poland (2007) 611-618. [\[PDF\]](pubs\enviroinfo-2007-2.pdf)

10. Yu-Chi Chu, Su-Mei Huang, Chin-Cheng Lien, and Chen-Chau Yang, "An Ontology-Driven Approach for Harmonizing and Integrating Environmental Information," *Proceedings of 21st International Conference of Informatics for Environmental Protection*, Warsaw, Poland (2007) 59-62. [\[PDF\]](pubs\enviroinfo-2007-1.pdf)

11. 連志誠, 黃素梅, 朱雨其, "本體導引式XML綱要之終端與非終端節點映射," *2007 國際資訊管理研討會*, 臺灣臺北 (2007).

12. 李連堯, 朱雨其, 王俊欽, "引用XML技術於環境水質監測資訊的交換及共享," *2006環境資訊研討會*, 臺灣臺中 (2006).

13. 朱雨其, 黃素梅, 連志誠, "服務導向之政府資訊系統整合架構 – 以污染源管理資訊系統為例," *第十屆資訊管理學術及警政資訊實務研討會*, 臺灣桃園 (2006) 599-113. [\[PDF\]](pubs\icim-2006.pdf)

14. 連志誠, 黃素梅, 朱雨其, "資料品質及資料淨化技術之探究-以環保部門資訊整合為例," *2006數位科技與創新管理國際研討會*, 臺灣臺北 (2006). [\[PDF\]](pubs\DT-2006.pdf)

15. 吳元彰, 朱雨其, 劉騏豪, 楊鍵樵, "應用基因演算法於時間序列之分群," *第十屆人工智慧與應用研討會*, 臺灣高雄 (2005).

16. 朱雨其, 黃素梅, 楊鍵樵, "植基知識本體之公部門資訊整合," 中華民國九十四年全國計算機會議, 臺灣臺南 (2005).

17. Yu-Chi Chu, Chea-Yuan Young, and Chen-Chau Yang, "Integrating Environmental Information through Data Warehousing with Data Quality Assurance,"  *Proceedings of the 16th International Conference of Informatics for Environmental Protection*, Vienna, Austria, (2002) 368-375. [\[PDF\]](pubs\EnviroInfo-2002.pdf)

18. Yu-Chi Chu, H. Featherstone, and Chen-Chau Yang,   "Implementing Internet-based e-Business Applications through the Coupling of Object Models and XML/EDI," *Proceedings of the ICS2000 Workshop on Computer Network, Internet, and Multimedia*, Chaiyi, Taiwan (2000) 199-206. [\[PDF\]](pubs\ICS-2000.pdf)

19. Yu-Chi Chu, H. Featherstone, and Chen-Chau Yang, "Coupling Object-oriented EDI with XML/EDI for Internet-based Electronic Business Implementation," *Proceedings of 11th Workshop on Object-Oriented Technology and Applications*, Taichung, Taiwan (2000) A9-A15. [\[PDF\]](pubs\OOT-2000.pdf)

20. 朱雨其, 蔡篤賢, 吳元彰, 鄭宏昇, 楊鍵樵, "建構動態資料檢集器以檢索蒐集網路資訊,"  *第五屆人工智慧與應用研討會*, 臺灣臺北 (2000) 669-676. [\[PDF\]](pubs\AI-2000.pdf)

21. Yu-Chi Chu, Shan-Shan Yang, and Chen-Chau Yang, "Ensuring data quality in data warehouses through attribute-based metadata and cost evaluation," *Int'l Conf. on Software Engineering and Knowledge Engineering* (SEKE'2000), Chicago, USA (2000) [\[PDF\]](pubs\SEKE-2000.pdf)

22. 朱雨其, 楊珊珊, 楊鍵樵, "資料倉儲環境中資料品質的評估機制," *中華民國八十八年全國計算機會議*, 臺灣臺北 (1999) A284-A291. [\[PDF\]](pubs\NCS-1999.pdf)

23. 朱雨其, 嚴國瑞, 江明洲, 楊鍵樵, "異質性資訊源環境中的資料擷取: 以調節器為基礎的方法," *分散式系統技術與應用研討會*, 臺灣臺南 (1998) 599-605. [\[PDF\]](pubs\DS-1998.pdf)

24. 朱雨其, 嚴國瑞, 連志誠, 楊鍵樵, "運用調節器整合異質性資訊源," *中華民國八十六年全國計算機會議*, 臺灣臺中 (1997) A66-A71. [\[PDF\]](pubs\NCS-1997.pdf)

25. Yu-Chi Chu, Chin-Cheng Lien, and Chen-Chau Yang,  "InfoHub: a flexible system for retrieving and integrating heterogeneous information sources,"  *Proceedings of Workshop on Distributed System Technologies and Applications*, Tainan, Taiwan (1997) 597-602. [\[PDF\]](pubs\DS-1997.pdf)

26. Jen-Chung Chen et al., "The application of GIS to watershed environmental management," *Proceedings of Int'l Symposium on Geographic Information System for Environment Protection*, Taipei, Taiwan (1995) 250-268. [\[PDF\]](pubs\GIS-1995.pdf)

27. S. H. Sheng et al., "A study on modification of river pollution index (RPI) ," *Proceedings of Republic of China - South Africa Bilateral Symposium on Water Resources*, Taipei, Taiwan (1994) 243-251. [\[PDF\]](pubs\RPI-1994.pdf)

28. Howard S. H. Chen,Yu-Chi Chu, and Huei-tsen Chiang, "Information policy and framework for environmental management in Taiwan,"  *EIM/EDI '94 Proceedings*, Taipei, Taiwan (1994) 1-5. [\[PDF\]](pubs\EDI-1994.pdf)

29. Howard S. H. Chen and Yu-Chi Chu, "Information management for environmental protection in Taiwan ," *Proceedings of Decision Support-2001 and 17th Annual Geographic Information Seminar*, Toronto, Canada (1994) 790-794. [\[PDF\]](pubs\GIS-1994.pdf)

30. 陳熙灝, 朱雨其, 惠龍, "環境地理資訊系統的發展與推動策略," *國土資訊系統研討會論文集*, 臺灣臺北 (1994) 143-150. [\[PDF\]](pubs\GIS-1994-1.pdf)

31. 陳熙灝, 黃世敏, 蔣慧珍, 朱雨其, "環保資訊系統之規劃及建置," 環保資訊系統研討會論文集, 臺灣臺北 (1991) 61-72. [\[PDF\]](pubs\EIS-1991.pdf)

### 學位論文

1.  博士論文：Intregrating Heterogeneous Information Sources through Ontology-Driven Model and Data Quality Analysis, 國立臺灣科技大學 電子工程研究所 計算機組 （2001） [\[LINK\]](https://hdl.handle.net/11296/7uv5zv)

2.  碩士論文：一個軟體系統時間限制的驗證方法, 國立臺灣工業技術學院 工程技術研究所（1993）[\[LINK\]](https://hdl.handle.net/11296/b58tpe)
