---
title: "臺灣遭受網路攻擊的次數？"
#author: "Yuchi Chu"
date: '2022-04-11'
format: 
  html:
    code-fold: true
featured: no
---


為了凸顯資通安全的重要，除了高舉「資安就是國安」這種口號外，公部門、學界及所謂的資安產業界最常用的招數，就是**標榜**臺灣是遭受網路攻擊的「重災區」。究竟臺灣被網路攻擊的次數是多少呢？以下是幾種說法：

### 立法委員和主政官員的說法[^1]

>吳委員琪銘：……針對資安及駭客的議題，這一陣子賴清德副總統受訪時說，臺灣每個月平均遭受高達3,000萬次駭客攻擊，這是全世界最高的……<br>
>主席：請行政院資通安全處簡處長說明。<br>
>簡處長宏偉：剛才您提到的那一個數字，僅是單一廠商的一個統計數字，根據我們自己的分析及蒐集，一天是遭受500萬次的攻擊及掃描，其實是更多的……

如果一天是500萬次攻擊，則每年是182億5千萬次攻擊；但根據110年資通安全技術年報[^2]，110年共「蒐集96億8千筆**攻擊**連線資訊」；這二項數據剛好差1倍，不知道是官員講錯了？還是年報算錯了？至於立委講的每月3000萬筆，一年是3億6千萬次，則又差得更遠了……

### 國外研究機構和網路媒體

> 1. 台灣每天受到超過2000萬次網路攻擊，境外假訊息攻擊世界第一多！這場資訊戰怎麼打？｜Taiwan Keywords EP11[^3]
> 2. 每分鐘 15 次的駭客攻擊，5G 世代的臺灣資安挑戰—資安所王仁甫策略總監專訪[^4]

以上2則報導分別來自「PanSci泛科學」的 YT 頻道和網站，其中第1則的資料說是來自瑞典某大學的研究機構，影片中並由某立法委員向國外人士強調攻擊次數是以「每一天」計算。每天2000萬次與前面官員所講的每天500萬次差了4倍! 其次，這則報導的標題强調「境外假訊息攻擊」，不知道這2000萬次的攻擊是否包括假訊息攻擊（認知作戰）？假訊息攻擊可以算是網路攻擊嗎？ 

第2則報導說每分鐘15次駭客攻擊，換算下來每天2萬多次，這和每天2000萬次也差太多了吧，似乎有點不太科學。後來看到PanSci泛科學 YT 頻道的說明：「本節目獲文化部辦理發展國際數位傳播補助」。OK, Got It!

### 資安或資訊業者的說法

> 製造業遭攻擊次數提升 軟體廠迎資安商機[^5]<br>
>根據國際資安大廠年中發布的調查，近9成企業曾發生資安問題，台灣也曾有台積電、電子產業、石化業遭資安攻擊。資安服務商安碁資訊（6690）表示，從前年起國內製造業被攻擊次數、程度加劇，今年攻擊次數更多、強度有增無減，因此今年製造業資安需求成長較為明顯。叡揚資訊（6752）則說，疫情下資安攻擊變多、企業重視程度提升，近3到5年需求續增。

「國際資安大廠」是那一家大廠啊？「近9成企業」的母數是全世界？還是全臺灣？「被攻擊次數、程度加劇，今年攻擊次數更多」具體的數字是多少？「疫情下資安攻擊變多」是有統計數據嗎？或者只是主觀的「感覺變多」？嚴格來看，這則報導基本上是一種「恐懼行銷」的手法。

其他關於臺灣遭受網路攻擊次數的統計、報導、研究、看法、見解……罄竹難書，但實際情況如何，似乎難有可令人信服的論據。從以上幾則例子來看，所謂的「網路攻擊次數」，大抵唬爛成分居多，甚至本身就構成一種「假訊息攻擊」。

### 原來如此!?

《網路安全的迷思和誤解》（暫譯）這本書裡說：「全球每天發生5,369次資料外洩, 8萬次網路攻擊」這種統計說詞是沒有意義的，何況這類說詞大多無法明確交待其來源及數據產生的過程[^6]。上述各種針對臺灣遭受網路攻擊次數的說詞，恰恰佐證了這項論點。

世界反運動禁藥機構（World Anti-Doping Agency）首任主席，加拿大籍的迪克．龐德（Dick Pound）曾經指稱：「有三分之一的冰球運動員非法使用藥物」，有記者問他這數據怎麼來的，他一點都不害羞地承認，那是他編出來的；「百分之20也好，百分之30也好，算我說謊」[^7]。龐德先生似乎認為只要「目的正確」，就可以不擇手段（說謊）。如此看來，網路攻擊次數這類數據會不會也是「編出來的」啊？


[^1]: 立法院第10屆第4會期內政委員會第14次全體委員會議紀錄，中華民國110年11月10日
[^2]: 行政院國家資通安全會報技術服中心，110年資通安全技術年報，中華民國111年7月，p.19
[^3]: https://www.youtube.com/watch?v=qMHsJGn5tc8 Accessed:2024.07.18
[^4]: https://pansci.asia/archives/331019 這篇報導係轉載科技大觀園網站：曾繁安，物聯網的資安攻防大戰！臺灣該如何見招拆招？Accessed:2024.07.18；原文並未提及「每分鐘15次駭客攻擊」。
[^5]: 自由時報 2022/11/07, https://ec.ltn.com.tw/article/breakingnews/4115381 Accessed:2024.07.18
[^6]: Spafford, E., L. Metcalf, J. Dykstra, Cybersecurity Myths and Misconceptions ( Chapter 14: Lies, Damn Lies, and Statistics), Addison-Wesley, 2023.
[^7]: 丹‧賈德納（Dan Gardner）, 李靜怡、黃慧慧譯，販賣恐懼-脫軌的風險判斷，博雅書屋，p.173, 台北，2009. 
