---
title: "所謂「情資」？"
#author: "Yuchi Chu"
date: '2025-04-30'
format: 
  html:
    code-fold: true
featured: no
---

> 你會相信某件事，是因為你需要相信；至於你相信或不信什麼，這本身並沒有價值，沒有功用。<br> 勒卡雷 《冷戰碟魂》

在公部門資訊單位工作，可能常常收到某些機構的通知，說是根據「情資」顯示，近期（例如520總統就職週年、雙十國慶、選舉投票日前…）將會有「密集網路攻擊」，提醒大家注意防範。但很少有人會問，這些所謂的「情資」是怎麼來的？

------------------------------------------------------------------------

間碟小說大師約翰．勒卡雷（John le Carre）在他的回憶錄《此生如鴿》裡講述了這麼個故事（可能是他的實際經驗）：英國情報局保有一個貼附在局長室墻上的綠色保險箱，據說裡面放著**極度機密**的東西，只有局長有籲匙能打開，但多年來從未有人見過此保險箱被打開過。後來由於情報局的大樓要拆除重建，就請現任局長將保險箱內東西取出，但現任局長說他根本沒有籲匙。於是只好去問歷任局長，不料他們都說從未持有該保險箱的籲匙，只知道該保險箱是二戰期間由當時的局長史都華．孟濟斯爵士（Stewart Menzies）下令裝設的。所以是孟濟斯爵士把鑰匙帶走了？而且和他一起下葬了嗎？

經過請示高層後，找來局內的「小偷」，保險箱以極其令人難堪的速度被打開了，但保險箱內卻空無一物。這是個障眼法嗎？經過資深官員檢視後，發現保險箱後面似乎另有蹊蹺，於是找來撬棍，將保險箱後牆面撬下來，赫然發現保險箱和牆面間有一條又厚又舊的灰色長褲。褲子上別了一張紙條，其上有打字機打的一段文字，宣稱這條褲子是希特勒的副手魯道夫．赫斯（Rudolf Hess）在1941年來英國時所穿的褲子。這段文字下方有一行用綠水墨水寫的字（依照慣例，只有局長能用綠色墨水）

**請分析，或許可以藉此瞭解德國紡織業的現況。**

------------------------------------------------------------------------

英國作家格雷安．葛林 (Graham Greene) 1958年的小說《哈瓦那特派員》(Our Friend in Havana) 講述冷戰期間，一名在古巴哈瓦那賣吸塵器的英國商人-伍爾摩的故事。伍爾摩人到中年，事業和婚姻都不順利，加上有個愛花錢的女兒，是以經濟上時見拮据。英國情報局的特工找上伍摩爾，請他蒐集哈瓦那當地的「情資」，並將支付他薪酬和費用（大抵是論件計酬的意思）。於是間碟打工仔伍爾摩開始杜撰各種情資，為了申請更多的費用，甚至發展下線情報網，「生意」越作越大。有一回，伍爾摩聲稱他「發現」了一個秘密軍事基地，並且附上該基地正在發展的毀滅性武器藍圖。但事實是，此藍圖是他將吸塵器拆開後，按其內部構件-吸嘴、噴氣口、套管等，依比例放大後所繪成（例如一英吋放大為三英呎）。

英國人收到此情資後，大為震驚，沒人知道古巴人想作什麼。大半天後，一位工作人員囁囁地指出，這不就像是個超大型的吸塵器嗎？長官一臉憂心地回答：「這就是我害怕的原因。」（他害怕什麼？）

> 插播一則新聞[^1]：軍情局２軍官虛構大陸情報人員、對話紀錄等假情資詐領上千萬獎金，如今被依貪汙罪判刑定讞，面臨牢獄之災……

[^1]: 聯合報，2025/02/21【重磅快評】情報員虛構假情資詐獎金 賴政府用假訊息抗中保台 https://udn.com/news/story/6656/8563710 Accessed:2025.02.24

------------------------------------------------------------------------

當然，以上二則可能都只是小說裡的「故事」，對於宣稱所謂網路攻擊的這類情資，我們還是必須「戒慎恐懼」，至於要不要相信這類情資，套一句葛林在他另一部小說《沉靜的美國人》裡所說的：「人遲早要選一邊站的，如果你還想當個人的話。」
