---
title: "IT 單位最「顧人怨」的事!？"
#author: "Yuchi Chu"
#date: '2022-04-11'
format: 
  html:
    code-fold: true
featured: no
---

企業中IT部門的「名聲」，隨時都遭遇各種挑戰。例如公司的網路設備故障，致使網路速度變慢甚或不通；賣場的POS裝置當機，造成顧客大排長龍；公務機關在下班前要發一份緊急公文，但電子公文交換系統卻無法運作。林林總總的突發情況，都讓人印象深刻，甚至對IT的管理和技術專長產生懷疑。此外，某些隱蔽的地方，通常是員工使用IT資源時遇到的「麻煩事」，這些日常的小事也可能讓員工抓狂，進而埋下顧人怨的種子，對IT部門的名聲同樣很傷。

Mark Settle[^1] 列舉了7項員工對IT部門最為不滿的事。當然，每個企的運營型態和組織文化不同，不能一概而論。以下是整理自該書的七種根源，再結合個人實務工作上的經驗和觀察，提出一些看法，供作參考。

[^1]: M. Settle, Truth from the Valley: A Practical Primer on Future IT Management Trends. 2020.

### 密碼

對多數員工而言，密碼是件麻煩事，甚至演變成噩夢。例如 ，放個長假回來帳號突然被鎖住，因為超過更改期限；久久用一次的系統，忘記先前設的密碼，打錯三次，帳號又被鎖住。其他像是密碼要求一定長度、規定要各種組合，三不五時就得改密碼等等這類瑣事，經常讓員工抓狂。但IT部門會認為密碼是一件嚴肅的事，特別是在「資安就是國安」這種口號下，這似乎是「必要的無奈」。至於密碼的複雜度、定期更改密碼這些措施對資安防護究竟有多少助益，倒是沒人探究。

### 報修單

員工向IT部門報修設備故障，倘若修復的時效不如預期，就會引發不滿。最常發生的抱怨是「已經報修好幾天了，都沒人處理」，可是有些「報修」並不見得都是IT設備的問題，有的員工連座位搬動，找條延長線都要報修（這類工作在新冠肺炎疫情期間尤為顯著），這些是IT部門的工作嗎？

### 視訊會議

每開一次視訊會議，就是一場大考驗。網路不通？畫面為什麼會有lag? 可不可以鏡頭自動對到現在發言者？主席講話時不能自動 loom in嗎？員工習慣將視訊會議當作「實體會議」看待，或是需要現場要有「導播」。是的，賣視訊設備的廠商會說這些都不是問題，當實際操作時，這些統統都是問題。

### 網路速度太慢 

公司對外連網的速度比員工在家裡或是用手機4G連網的速度還慢；員工在家辦公連到公司後台系統的速度超慢；新聞公關部門要對外直播，網路頻寬不夠，畫面與聲音沒法同步；這些都是常見的反應。但網路速度究竟要多快才算快？直播如果用專線，由哪個部門買單？

### 網站被阻擋

員工在外部環境習慣了自由自在的網路「衝浪」，他們認為在工作環境也應該提供相同的服務和自由。哪些網站能造訪，哪些不能造訪，每個人看法不儘相同（為什麼不能連結購物網站？為什麼不能看抖音？）這種期待與現實的落差，間接造成對IT部門的不滿。

### 印表機

又卡紙了、又沒墨水了，馬上要開會了，資料還是印不出來；為什麼沒有彩色印表機？為什麼不能列印A3的報表？這類問題也多由IT部門承擔。由於愈來愈多的工作場所推行「無紙化」或所謂「電子會議」，對印表機的挫折感正逐漸減少，但要完全解決印表機問題，只怕得再等一段時日。

### 員說通訊錄（列表）的正確性

公司內通常會維護所有員工的通訊資料，例如，職稱、電話分機等，這些資料如果發生錯誤或未能及時更新，通常也會怪到IT部門頭上。此外，公司客戶的連絡資料，或是公務機關電子公文交換的「地址簿」，這類資料的維護究竟應該如何分工？如何課責？如果沒有一套完整的作業流程和核校機制，IT部門就成為是最直接的「砲灰」。

當然不止以上七件事。如果單就以上七件事來看，有少部分可以藉由引進新技術加以改善（密碼管理或重置），部分問題可能是程序和制度面的問題，需要設計明確的作業流程及課責制度。IT管理工作要想完全免除「顧人怨」，並不容易。

